on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Test action
    outputs:
      keys: ${{ steps.hello.outputs.keys }}
      changed: ${{ steps.hello.outputs.changed }}
      tag: ${{ steps.hello.outputs.releaseOrSlug }}
      sha: ${{ steps.hello.outputs.sha }}
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          token: ${{ github.token }}
          exec: |
            options:
              - on:
                  files:
                  - key: ci
                    files:
                    - '.github/**/*.y?(a)ml'
                    match: all
                  - key: action
                    files:
                    - "!.github"
                    - "**/*.[tj]s"
                  push:
                    branches:
                    - main
                    - dev
                    tags:
                    - /v\d+\.\d+\.\d+$/
  check:
    runs-on: ubuntu-latest
    name: Check outputs
    needs:
    - hello
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.hello.outputs.changed) }}
    steps:
    - uses: actions/checkout@v2
    - name: Check Subproject
      run: |
        echo "${{ needs.hello.outputs.tag }}"
        echo "${{ needs.hello.outputs.sha }}"
        echo "${{ matrix.key }}"
        echo "${{ toJson(matrix.changed) }}"
