on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Test action
    outputs:
      keys: ${{ steps.hello.outputs.keysMatrix }}
      matches: ${{ steps.hello.outputs.matchesMatrix }}
      tag: ${{ steps.hello.outputs.releaseOrSlug }}
      sha: ${{ steps.hello.outputs.sha }}
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          token: ${{ github.token }}
          exec: |
            options:
              - on:
                  files:
                  - key: ci
                    files:
                    - '.github/**/*.y?(a)ml'
                    match: all
                  - key: action
                    files:
                    - "!.github"
                    - "**/*.[tj]s"
                  push:
                    branches:
                    - main
                    - dev
              - on:
                  push:
                    tags:
                    - /v\d+\.\d+\.\d+$/
  check-matrix:
    if: startsWith( github.ref, 'refs/heads/' )
    runs-on: ubuntu-latest
    name: Check matrix outputs
    needs:
    - hello
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.hello.outputs.matches) }}
    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: |
        echo "${{ needs.hello.outputs.tag }}"
        echo "${{ needs.hello.outputs.sha }}"
        echo "${{ needs.hello.outputs.keys }}"
        echo "${{ toJson(matrix.match) }}"
  check-outputs:
    runs-on: ubuntu-latest
    name: Check outputs
    needs:
    - hello
    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: |
        echo "tag: ${{ needs.hello.outputs.tag }}"
        echo "sha: ${{ needs.hello.outputs.sha }}"
        echo "keys: ${{ needs.hello.outputs.keys }}"
        echo "matches: ${{ toJson(needs.hello.outputs.matches) }}"
